### ISSUE TITLE
Unable to kill / invalid handle

### ISSUE THREAD

**Issue by Neo23x0** [Neo23x0/Raccine#77]
@Eran-YT 

There's a problem in blocking mode. Raccine is unable to end itself. 

![Screenshot 2020-10-27 093019](https://user-images.githubusercontent.com/2851492/97276880-12592780-1838-11eb-87a5-b73147daf549.png)

Caused at this position by an invalid handle.

![Screenshot 2020-10-27 093638](https://user-images.githubusercontent.com/2851492/97276835-040b0b80-1838-11eb-8ac7-7f68b7f12fe4.png)

![Screenshot 2020-10-27 093609](https://user-images.githubusercontent.com/2851492/97276864-0b321980-1838-11eb-96f8-719cffbf1111.png)

**Comment by JohnLaTwC** [comment]
The crash is due to a double-close on the wrapped process handle returned from createChildProcessWithDebugger.  When this function is about to return, the destructor is called on ProcessHandleWrapper and ThreadHandleWrapper.  The destructor calls `Close()` which calls `CloseHandle` on the process handle.  Later in main when `hProcess` goes out of scope, the destructor is called again which results in the double-close on handle.  

```
    ~HandleWrapper()
    {
        Close();
    }

    void Close()
    {
        if (m_handle != traits::InvalidValue) {
            traits::Close(m_handle);
            m_handle = traits::InvalidValue;
        }
    }

...
struct ProcessHandleTraits
{
    typedef HANDLE HandleType;
    inline static const HANDLE InvalidValue = NULL;

    static void Close(HANDLE value)
    {
        CloseHandle(value); <<<<<<<<<<<<<<<<<<
    }
};
```

The `phProcess` param is declared as pass by reference so need to understand why a temp `ProcessHandleWrapper` is allocated and destroyed during `createChildProcessWithDebugger`.
```
DWORD createChildProcessWithDebugger(std::wstring command_line,
                                    DWORD dwAdditionalCreateParams,
                                    ProcessHandleWrapper& phProcess,
                                    ThreadHandleWrapper& phThread)
```


![image](https://user-images.githubusercontent.com/16035087/97319617-49284100-182a-11eb-8c80-1e8330a586cd.png)
